name: speaking_hand
description: "A new Flutter project to recognize hand gestures and convert them to speech."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  isolate_handler:
  image: ^4.5.4
  tflite_flutter:
  http: ^1.3.0
  flutter_tts: ^4.2.2
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
